name: BugkuAutoSignIn

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 15 * * *

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'setup python'
      uses: actions/setup-python@master
      with: 
        python-version: 3.7
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: SignIn
      run: |
        sed -i 's|SCKEY = ""|SCKEY = "${{ secrets.SCKEY }}"|' auto_logon.py
        sed -i 's|GITC = ""|GITC = "${{ secrets.GITC }}"|' auto_logon.py
        sed -i 's|USER = ""|USER = "${{ secrets.USER }}"|' auto_logon.py
        python3 auto_login.py
        done